title: Walletify Legal
description: Legal documents for the Walletify portfolio tracker app.
url: "https://www.walletify.org"
baseurl: ""
theme: jekyll-theme-minimal
permalink: /:basename

defaults:
  - scope:
      path: ""
    values:
      layout: default
