title: Walletify Portfolio
description: "BIST, ABD hisseleri, fonlar, döviz ve metaller için sade portföy takip uygulaması."
url: "https://www.walletify.org"
baseurl: ""
theme: jekyll-theme-minimal
permalink: /:basename

defaults:
  - scope:
      path: ""
    values:
      layout: default
